### ISSUE TITLE
cannot clone the package directly

### ISSUE THREAD

**Issue by crsl4** [klkeys/IHT.jl#2]
The package cannot be installed with `Pkg.clone("https://github.com/klkeys/IHT.jl.git")` as it depends on two other packages that are not in METADATA. So, in order to install the package, one needs to do:
```
Pkg.clone("https://github.com/klkeys/PLINK.jl.git")
Pkg.clone("https://github.com/klkeys/RegressionTools.jl.git")
Pkg.clone("https://github.com/klkeys/IHT.jl.git")
```
in this order.
If you started with `Pkg.clone("https://github.com/klkeys/IHT.jl.git")`, you would need to remove the `IHT` folder in the `.julia` path, before trying again in the specific order above.
It would be nice to have this info in the documentation!

**Comment by klkeys** [comment]
Done. See commit https://github.com/klkeys/IHT.jl/commit/9430414ef4019733e620e3596717a2ba5b64783c.
